# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d1d90be4086c6052bd43b184f6a0d5a2772fe469b7c910d624f7f33fac4cda7688598ad31ee42958db5951188eaa718887d4dcb8dd48df42bc4b3466201cfbf
  gplus_oauth:
      client_id: na
      client_secret: na

test:
  secret_key_base: bdc3adcf1c9b35537ebc2213ed7dbbaa764557172e59daa56412378be6222ba9863e113847b12d9058cf9580b41865f67a8987b69738a4ee367cfb7fd4f22d48
  gplus_oauth:
      client_id: na
      client_secret: na

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  gplus_oauth:
      client_id: <%= ENV["GPLUS_CLIENTID"] %>
      client_secret: <%= ENV["GPLUS_CLIENTSECRET"] %>
